### PR TITLE
Travisify

### PR DESCRIPTION
**Pull request by pezholio**
All green!

### CODE REVIEW

**Comment by Floppy** [comment]
Is this safe to merge now? What will be uploaded after a successful build, anything? Should we be scared? Anyone know?

**Comment by pezholio** [comment]
Yeah, it should run `rake berkshelf:upload` on a successful build on master. Whether this will work though is anyone's guess

**Comment by Floppy** [comment]
I'll check the versions tomorrow before I merge... unless you get to it first.

**Comment by pezholio** [comment]
It's version 0.5.0 on the Chef server and 0.5.0 here, so that should be OK right?

**Comment by Floppy** [comment]
can you tell if it's frozen? Also, dependencies.

**Comment by Floppy** [comment]
I suspect it's fine, but just so we know what to expect.

**Pull request closed without merging**
